### PR TITLE
Shared table implementation

### PR DESCRIPTION
**Pull request by VoidedBlades**
Shared table global keyword support, vulnerability fixes and change from onReady to onDidChangeState as a result from onReady being removed on package update.

### CODE REVIEW

**Comment by NightrainsRbx** [comment]
This isn't the right way to define it, DataTypes would go in: https://github.com/NightrainsRbx/RobloxLsp/blob/master/server/api/DataTypes.json

The rest globals would go env.luau

Also, why is the change of onReady?

**Comment by VoidedBlades** [comment]
My bad, will adjust the data type in a second.

The onReady change was made after updating the packages (whom on install prior to that mentioned security vulnerabilities) where errors were presented during debugging that onReady was no longer present as a usable connection as stated in the commit message.

Due to that it was required to change over to onDidStateChange and check if the state changed to Running.

**Comment by TheCoderCat418** [comment]
This would be very helpful, any plans to merge this?

**Comment by NightrainsRbx** [comment]
This would still be wrong since you are declaring the methods where the constructors are declared, I will close this because another PR for this has been merged.

**Pull request closed without merging**
